### ISSUE TITLE
西班牙语支持

### ISSUE THREAD

**Issue by junpengxx** [robbinhan/bob-anki#2]
请问能不能增加其他API以支持西班牙语翻译与Anki的收录

**Comment by Junpeng8** [comment]
比如西语助手

**Comment by robbinhan** [comment]
好的，我尽快调研下

**Comment by aaabbb0088** [comment]
安裝在anki上的插件，目前無法下載。
之後會再開放下載嗎？感謝。

**Comment by robbinhan** [comment]
你是指anki connect吗？这个是可以下载的，可以看下官方文档，直接在anki输入编号就可以。
https://ankiweb.net/shared/info/2055492159

**Comment by aaabbb0088** [comment]
了解，感謝
