### ISSUE TITLE
關於如何使用

### ISSUE THREAD

**Issue by macOSWk** [robbinhan/bob-anki#5]
使用時開啓anki    bob和瀏覽器還需要安裝插件
<img width="689" alt="截屏2022-05-20 11 08 59" src="https://user-images.githubusercontent.com/86730293/169443390-12f7baee-5066-4f88-be4b-7e725813e419.png">
碼

**Comment by robbinhan** [comment]
是的，安装AnkiConnect后，保持打开anki即可。

PS：最新版0.0.3版本在Anki关闭下也可以保存在文件中，后续再打开Anki时再导入也可以

**Comment by xiezuan** [comment]
1.安装AnkiConnect
